In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder, LabelEncoder
import pickle

WARNING:tensorflow:From c:\ANN Project\venv\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

In [2]:
data = pd.read_csv('Churn_Modelling.csv')
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [3]:
# Delete the unnecessary columns
data = data.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1)

In [4]:
data.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [5]:
# Encode Categorical variables
label_encoder_gen = LabelEncoder()
data['Gender'] = label_encoder_gen.fit_transform(data['Gender'])
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [6]:
# One Hot Encoder
onehot_encoder_geograph = OneHotEncoder(handle_unknown = 'ignore')
geo_encoded = onehot_encoder_geograph.fit_transform(data[['Geography']]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded, columns = onehot_encoder_geograph.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [7]:
# Combine onehot encoded data 
data = pd.concat([data.drop('Geography', axis = 1), geo_encoded_df], axis = 1)

In [8]:
data

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,0,1.0,0.0,0.0
9996,516,1,35,10,57369.61,1,1,1,101699.77,0,1.0,0.0,0.0
9997,709,0,36,7,0.00,1,0,1,42085.58,1,1.0,0.0,0.0
9998,772,1,42,3,75075.31,2,1,0,92888.52,1,0.0,1.0,0.0
9999,792,0,28,4,130142.79,1,1,0,38190.78,0,1.0,0.0,0.0

In [9]:
# Split the data into features and target
X = data.drop('EstimatedSalary', axis = 1)
y = data['EstimatedSalary']

In [10]:
# Split the data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y ,test_size=0.2, random_state=42)

In [11]:
# Scaling the features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [12]:
# Save all the pickle files
with open('label_encoder_gen.pkl', 'wb') as file:
    pickle.dump(label_encoder_gen, file)

with open('onehot_encoder_geograph', 'wb') as file:
    pickle.dump(onehot_encoder_geograph, file)

with open('scaler.pkl', 'wb') as file:
    pickle.dump(scaler, file)

In [13]:
# Train the ANN with regression problem

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [14]:
# Built the model

model = Sequential ([
    Dense(64, activation = 'relu', input_shape = (X_train.shape[1],)),
    Dense(32, activation = 'relu'),
    Dense(1) # if no activation is applied then liner activation is applied 
])

# compile the model

model.compile(optimizer = 'adam', loss = 'mean_absolute_error', metrics = ['mae'])

model.summary()

WARNING:tensorflow:From c:\ANN Project\venv\Lib\site-packages\keras\src\backend.py:873: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

WARNING:tensorflow:From c:\ANN Project\venv\Lib\site-packages\keras\src\optimizers\__init__.py:309: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 64)                832

 dense_1 (Dense)             (None, 32)                2080

 dense_2 (Dense)             (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [15]:
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

# Srt up Tensorboard
log_dir = "regressionlogs/fit/" + datetime.datetime.now().strftime("%Y%m%d - %H%M%S")
tensorboard_callback = TensorBoard(log_dir = log_dir, histogram_freq = 1)

In [16]:
# Setting up validation loss
early_stopping_callback = EarlyStopping(monitor = 'val_loss', patience = 10, restore_best_weights = True)

In [17]:
# Train the model 

history = model.fit(X_train, y_train,
    validation_data = (X_test, y_test),
    epochs = 100,
    callbacks = [early_stopping_callback, tensorboard_callback]
)

Epoch 1/100
WARNING:tensorflow:From c:\ANN Project\venv\Lib\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.

WARNING:tensorflow:From c:\ANN Project\venv\Lib\site-packages\keras\src\engine\base_layer_utils.py:384: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

250/250 [==============================] - 3s 5ms/step - loss: 100387.0312 - mae: 100387.0312 - val_loss: 98552.4062 - val_mae: 98552.4062
Epoch 2/100
250/250 [==============================] - 1s 3ms/step - loss: 99755.1328 - mae: 99755.1328 - val_loss: 97266.8906 - val_mae: 97266.8906
Epoch 3/100
250/250 [==============================] - 1s 3ms/step - loss: 97495.6484 - mae: 97495.6484 - val_loss: 93936.6797 - val_mae: 93936.6797
Epoch 4/100
250/250 [==============================] - 1s 3ms/step - loss: 92994.3672 - mae: 92994.3672 - val_loss: 88280.9531 - val_mae: 88280.9531
Epoch 5/100
250/250 [==============================] - 1s 4ms/step - loss: 86272.0469 - mae: 86272.0469 - val_loss: 80791.5078 - val_mae: 80791.5078
Epoch 6/100
250/250 [==============================] - 1s 4ms/step - loss: 78072.7578 - mae: 78072.7578 - val_loss: 72525.2969 - val_mae: 72525.2969
Epoch 7/100
250/250 [==============================] - 1s 4ms/step - loss: 69655.7344 - mae: 69655.7344 - val_loss: 64796.9961 - val_mae: 64796.9961
Epoch 8/100
250/250 [==============================] - 1s 4ms/step - loss: 62198.7891 - mae: 62198.7891 - val_loss: 58641.6211 - val_mae: 58641.6211
Epoch 9/100
250/250 [==============================] - 1s 3ms/step - loss: 56717.8242 - mae: 56717.8242 - val_loss: 54542.8867 - val_mae: 54542.8867
Epoch 10/100
250/250 [==============================] - 1s 3ms/step - loss: 53452.3672 - mae: 53452.3672 - val_loss: 52279.8203 - val_mae: 52279.8203
Epoch 11/100
250/250 [==============================] - 1s 3ms/step - loss: 51748.4375 - mae: 51748.4375 - val_loss: 51278.7344 - val_mae: 51278.7344
Epoch 12/100
250/250 [==============================] - 1s 3ms/step - loss: 50938.3555 - mae: 50938.3555 - val_loss: 50882.1328 - val_mae: 50882.1328
Epoch 13/100
250/250 [==============================] - 1s 3ms/step - loss: 50580.4023 - mae: 50580.4023 - val_loss: 50754.9648 - val_mae: 50754.9648
Epoch 14/100
250/250 [==============================] - 1s 3ms/step - loss: 50417.2930 - mae: 50417.2930 - val_loss: 50713.5391 - val_mae: 50713.5391
Epoch 15/100
250/250 [==============================] - 1s 3ms/step - loss: 50317.4102 - mae: 50317.4102 - val_loss: 50675.2422 - val_mae: 50675.2422
Epoch 16/100
250/250 [==============================] - 1s 3ms/step - loss: 50244.6055 - mae: 50244.6055 - val_loss: 50630.0391 - val_mae: 50630.0391
Epoch 17/100
250/250 [==============================] - 1s 2ms/step - loss: 50185.1680 - mae: 50185.1680 - val_loss: 50588.6367 - val_mae: 50588.6367
Epoch 18/100
250/250 [==============================] - 1s 2ms/step - loss: 50136.2969 - mae: 50136.2969 - val_loss: 50565.9727 - val_mae: 50565.9727
Epoch 19/100
250/250 [==============================] - 1s 2ms/step - loss: 50090.3477 - mae: 50090.3477 - val_loss: 50532.8672 - val_mae: 50532.8672
Epoch 20/100
250/250 [==============================] - 1s 2ms/step - loss: 50049.4492 - mae: 50049.4492 - val_loss: 50508.0586 - val_mae: 50508.0586
Epoch 21/100
250/250 [==============================] - 1s 2ms/step - loss: 50015.5156 - mae: 50015.5156 - val_loss: 50466.8125 - val_mae: 50466.8125
Epoch 22/100
250/250 [==============================] - 1s 2ms/step - loss: 49981.9219 - mae: 49981.9219 - val_loss: 50450.6484 - val_mae: 50450.6484
Epoch 23/100
250/250 [==============================] - 1s 3ms/step - loss: 49955.4141 - mae: 49955.4141 - val_loss: 50418.0000 - val_mae: 50418.0000
Epoch 24/100
250/250 [==============================] - 1s 3ms/step - loss: 49930.6445 - mae: 49930.6445 - val_loss: 50404.7383 - val_mae: 50404.7383
Epoch 25/100
250/250 [==============================] - 1s 3ms/step - loss: 49903.4453 - mae: 49903.4453 - val_loss: 50388.7109 - val_mae: 50388.7109
Epoch 26/100
250/250 [==============================] - 1s 3ms/step - loss: 49879.8242 - mae: 49879.8242 - val_loss: 50383.4727 - val_mae: 50383.4727
Epoch 27/100
250/250 [==============================] - 1s 3ms/step - loss: 49857.8516 - mae: 49857.8516 - val_loss: 50368.5234 - val_mae: 50368.5234
Epoch 28/100
250/250 [==============================] - 1s 3ms/step - loss: 49837.7969 - mae: 49837.7969 - val_loss: 50352.1055 - val_mae: 50352.1055
Epoch 29/100
250/250 [==============================] - 1s 2ms/step - loss: 49816.4609 - mae: 49816.4609 - val_loss: 50344.9844 - val_mae: 50344.9844
Epoch 30/100
250/250 [==============================] - 1s 2ms/step - loss: 49798.2734 - mae: 49798.2734 - val_loss: 50334.0898 - val_mae: 50334.0898
Epoch 31/100
250/250 [==============================] - 1s 2ms/step - loss: 49780.8008 - mae: 49780.8008 - val_loss: 50320.7383 - val_mae: 50320.7383
Epoch 32/100
250/250 [==============================] - 1s 2ms/step - loss: 49762.6055 - mae: 49762.6055 - val_loss: 50318.9297 - val_mae: 50318.9297
Epoch 33/100
250/250 [==============================] - 1s 2ms/step - loss: 49747.8477 - mae: 49747.8477 - val_loss: 50316.8281 - val_mae: 50316.8281
Epoch 34/100
250/250 [==============================] - 1s 2ms/step - loss: 49731.5781 - mae: 49731.5781 - val_loss: 50312.4297 - val_mae: 50312.4297
Epoch 35/100
250/250 [==============================] - 1s 2ms/step - loss: 49716.3242 - mae: 49716.3242 - val_loss: 50298.0781 - val_mae: 50298.0781
Epoch 36/100
250/250 [==============================] - 1s 3ms/step - loss: 49700.9023 - mae: 49700.9023 - val_loss: 50299.3281 - val_mae: 50299.3281
Epoch 37/100
250/250 [==============================] - 1s 3ms/step - loss: 49688.0703 - mae: 49688.0703 - val_loss: 50290.2031 - val_mae: 50290.2031
Epoch 38/100
250/250 [==============================] - 1s 2ms/step - loss: 49676.0469 - mae: 49676.0469 - val_loss: 50296.0039 - val_mae: 50296.0039
Epoch 39/100
250/250 [==============================] - 1s 2ms/step - loss: 49663.7695 - mae: 49663.7695 - val_loss: 50297.1641 - val_mae: 50297.1641
Epoch 40/100
250/250 [==============================] - 1s 2ms/step - loss: 49651.0234 - mae: 49651.0234 - val_loss: 50291.3789 - val_mae: 50291.3789
Epoch 41/100
250/250 [==============================] - 1s 2ms/step - loss: 49641.0703 - mae: 49641.0703 - val_loss: 50290.2422 - val_mae: 50290.2422
Epoch 42/100
250/250 [==============================] - 1s 2ms/step - loss: 49627.0625 - mae: 49627.0625 - val_loss: 50298.5781 - val_mae: 50298.5781
Epoch 43/100
250/250 [==============================] - 1s 2ms/step - loss: 49618.4727 - mae: 49618.4727 - val_loss: 50294.7344 - val_mae: 50294.7344
Epoch 44/100
250/250 [==============================] - 1s 2ms/step - loss: 49605.6680 - mae: 49605.6680 - val_loss: 50288.2891 - val_mae: 50288.2891
Epoch 45/100
250/250 [==============================] - 1s 2ms/step - loss: 49597.4492 - mae: 49597.4492 - val_loss: 50287.0234 - val_mae: 50287.0234
Epoch 46/100
250/250 [==============================] - 1s 2ms/step - loss: 49589.1797 - mae: 49589.1797 - val_loss: 50288.0391 - val_mae: 50288.0391
Epoch 47/100
250/250 [==============================] - 1s 2ms/step - loss: 49577.3359 - mae: 49577.3359 - val_loss: 50279.5742 - val_mae: 50279.5742
Epoch 48/100
250/250 [==============================] - 1s 2ms/step - loss: 49567.7461 - mae: 49567.7461 - val_loss: 50277.0664 - val_mae: 50277.0664
Epoch 49/100
250/250 [==============================] - 1s 2ms/step - loss: 49560.9844 - mae: 49560.9844 - val_loss: 50277.8203 - val_mae: 50277.8203
Epoch 50/100
250/250 [==============================] - 1s 2ms/step - loss: 49550.4883 - mae: 49550.4883 - val_loss: 50271.9375 - val_mae: 50271.9375
Epoch 51/100
250/250 [==============================] - 1s 2ms/step - loss: 49543.2227 - mae: 49543.2227 - val_loss: 50281.4648 - val_mae: 50281.4648
Epoch 52/100
250/250 [==============================] - 1s 2ms/step - loss: 49533.6797 - mae: 49533.6797 - val_loss: 50288.1211 - val_mae: 50288.1211
Epoch 53/100
250/250 [==============================] - 1s 2ms/step - loss: 49526.4531 - mae: 49526.4531 - val_loss: 50274.9258 - val_mae: 50274.9258
Epoch 54/100
250/250 [==============================] - 1s 2ms/step - loss: 49521.4414 - mae: 49521.4414 - val_loss: 50281.0391 - val_mae: 50281.0391
Epoch 55/100
250/250 [==============================] - 1s 2ms/step - loss: 49511.3320 - mae: 49511.3320 - val_loss: 50285.4258 - val_mae: 50285.4258
Epoch 56/100
250/250 [==============================] - 1s 2ms/step - loss: 49505.8750 - mae: 49505.8750 - val_loss: 50267.2031 - val_mae: 50267.2031
Epoch 57/100
250/250 [==============================] - 1s 2ms/step - loss: 49495.0703 - mae: 49495.0703 - val_loss: 50279.3711 - val_mae: 50279.3711
Epoch 58/100
250/250 [==============================] - 1s 2ms/step - loss: 49489.7969 - mae: 49489.7969 - val_loss: 50275.5352 - val_mae: 50275.5352
Epoch 59/100
250/250 [==============================] - 1s 2ms/step - loss: 49482.3750 - mae: 49482.3750 - val_loss: 50278.5352 - val_mae: 50278.5352
Epoch 60/100
250/250 [==============================] - 1s 2ms/step - loss: 49473.6328 - mae: 49473.6328 - val_loss: 50277.7266 - val_mae: 50277.7266
Epoch 61/100
250/250 [==============================] - 1s 2ms/step - loss: 49467.4062 - mae: 49467.4062 - val_loss: 50279.3477 - val_mae: 50279.3477
Epoch 62/100
250/250 [==============================] - 1s 2ms/step - loss: 49463.2461 - mae: 49463.2461 - val_loss: 50281.3242 - val_mae: 50281.3242
Epoch 63/100
250/250 [==============================] - 1s 2ms/step - loss: 49455.0430 - mae: 49455.0430 - val_loss: 50278.3438 - val_mae: 50278.3438
Epoch 64/100
250/250 [==============================] - 1s 3ms/step - loss: 49450.2578 - mae: 49450.2578 - val_loss: 50276.2422 - val_mae: 50276.2422
Epoch 65/100
250/250 [==============================] - 1s 2ms/step - loss: 49444.3906 - mae: 49444.3906 - val_loss: 50287.1328 - val_mae: 50287.1328
Epoch 66/100
250/250 [==============================] - 1s 2ms/step - loss: 49440.8438 - mae: 49440.8438 - val_loss: 50277.6875 - val_mae: 50277.6875

In [18]:
%load_ext tensorboard

In [19]:
%tensorboard --logdir regressionlogs/fit

Reusing TensorBoard on port 6007 (pid 35060), started 1:52:58 ago. (Use '!kill 35060' to kill it.)

In [20]:
## Evaluate the model on the test data

test_loss, test_mae = model.evaluate(X_test, y_test)
print(f"Test Mae : {test_mae}")

63/63 [==============================] - 0s 2ms/step - loss: 50267.2031 - mae: 50267.2031
Test Mae : 50267.203125

In [21]:
## Saving the regression model
model.save("regression_model.h5")

c:\ANN Project\venv\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

In [22]:
print(type(onehot_encoder_geograph))
print(onehot_encoder_geograph)

<class 'sklearn.preprocessing._encoders.OneHotEncoder'>
OneHotEncoder(handle_unknown='ignore')

In [23]:
print(hasattr(onehot_encoder_geograph, "categories_"))

True